### ISSUE TITLE
Archive completion doesn't work with $BORG_REPO

### ISSUE THREAD

**Issue by SanskritFritz** [mrkmg/borgbackup-zsh-completion#3]
You check the README for "This is a Borg repository". It is not suitable for this scenario:
```
export BORG_REPO=borgrepo
borg list ::archive
```
I solved this by simply trusting borg for knowing if the directory is a repo 😄 

https://github.com/mrkmg/borgbackup-zsh-completion/blob/3074cde45585f175c5ab2d655c5fdb4d723ebbec/_borg#L236

**Comment by mrkmg** [comment]
From my testing, it does not appear that I can access ENV variables from withen the ZSH autocomplete function. I am still testing.

**Comment by SanskritFritz** [comment]
You have to export the variable, just setting it is not enough, autocompletion works in a subshell I think.

**Comment by SanskritFritz** [comment]
Closing, this is solved.
