### ISSUE TITLE
recreate is missing, change-passphrase is a subcommand of key

### ISSUE THREAD

**Issue by SanskritFritz** [mrkmg/borgbackup-zsh-completion#4]
https://github.com/mrkmg/borgbackup-zsh-completion/blob/7c04db1f5560edff68b5e71b610f0a28e4c5fda8/_borg#L62

**Comment by SanskritFritz** [comment]
Should I open the same issue at borg as well?

**Comment by mrkmg** [comment]
I’ll take care of it this weekend

**Comment by SanskritFritz** [comment]
I actually started working on it, and got pretty far. I also reorganized it to follow the documentation more closely, so a review is much easier this way.
Do you want me to open a pull request?

**Comment by mrkmg** [comment]
Sure! Thanks.

**Comment by SanskritFritz** [comment]
Here you go: #5
