### ISSUE TITLE
parse error near `;;'

### ISSUE THREAD

**Issue by rbange** [mrkmg/borgbackup-zsh-completion#6]
I loaded the latest version and put it to `/usr/local/share/zsh/site-functions`

When trying out I get following error
```
> borg i
_borg:112: parse error near `;;'
_borg:112: parse error near `;;'
_borg:112: parse error near `;;'
```

The file looks well formatted for me. Any idea?

**Comment by mrkmg** [comment]
Very odd. I am not sure why that would error there. I am no pro at zsh completion scripts. I am not sure how to help.

**Comment by rbange** [comment]
Mhh I tried a lot and did not get your version to work :/

Nevertheless I saw that there is also a zsh-completion file in the official borg repo:
https://github.com/borgbackup/borg/blob/master/scripts/shell_completions/zsh/_borg
which also works for me.

Details:
``borg 1.1.9``
``zsh 5.7.1 (x86_64-apple-darwin18.2.0)``

Thanks for your help anyways :)

**Comment by mrkmg** [comment]
That version is a fork of this one, but maintained. Better to use that.

**Comment by SamK** [comment]
I there, just for your information, the issue is due to some in-code comments located below lines that expect a line continuation (because of the `\` character at the end).

This is an example of was I am talking about:
https://github.com/mrkmg/borgbackup-zsh-completion/blob/master/_borg#L89
